### ISSUE TITLE
Footer disappeared

### ISSUE THREAD

**Issue by skippskipp** [Tangerine-Community/Tangerine-client#189]
The app footer seems to have disappeared from all screens:

![screenshot_2016-01-04-13-45-11](https://cloud.githubusercontent.com/assets/2474753/12097727/45178746-b2eb-11e5-87e3-b393714bdb86.png)

**Comment by chrisekelley** [comment]
I confirmed this issue with the build on tree (i.e. clicking apk and using the download http://159.203.15.226/apk/ohmuda.arm )
I built and tested a local apk and also reproduced this issue. 
Strange that the footer displays fine on the local dev web version.

**Comment by chrisekelley** [comment]
Using inspect with Chrome (chrome://inspect/#devices) initially the footer does not display; however, the html code for the footer is viewable in the source. Refreshing the browser instance makes the footer appear. Could this be an issue with the width of the version number?

(an aside: While searching for version.js, I ran into this code from pouch that is a clever way to extract the version from package.json:

module.exports = require('../package.json').version;
)

**Comment by chrisekelley** [comment]
The issue is probably not the version number width. I compared earlier screenshots and the version number width is the same. 

Here is a build from 2015-11-20:
![screenshot_2015-11-20-12-59-41](https://cloud.githubusercontent.com/assets/861535/12115551/8c925902-b3b3-11e5-95cd-eb1d0a4bb214.png)

Here is the latest version:
![screenshot_2016-01-05-13-45-01](https://cloud.githubusercontent.com/assets/861535/12115563/95df55e6-b3b3-11e5-8e03-634f35587b11.png)

Now when I close the app, remove it from the app menu, and restart it, the footer displays!

**Comment by chrisekelley** [comment]
Now I can reproduce this error on the local web dev. platform. Needed to logout first. Progress...

**Comment by chrisekelley** [comment]
onClose was showing the footer after the user logs in, which closes the Login view. Marionette has changed the onClose method to onBeforeDestroy.

**Comment by chrisekelley** [comment]
Footer now displays in web dev and apk version. Screenshot from apk version:
![tang-back-button-with-footer](https://cloud.githubusercontent.com/assets/861535/12142510/e4a20db6-b478-11e5-8adf-d935ec777f15.png)
