### ISSUE TITLE
Improvements to the Universal Uploads process

### ISSUE THREAD

**Issue by chrisekelley** [Tangerine-Community/Tangerine-client#252]
- [x] Improve understanding of corsbulkuploads.rb
- [x] Consider more logging of errors
- [x] Improve user interface to pinpoint where bulk upload process fails. See #247

**Comment by rjcorwin** [comment]
I'm still trying to understand why corsbulkuploads.rb is needed. The reasoning that CouchDB 1.2 didn't have support for CORS doesn't seem to be it because from a Cordova context, same origin policies for XHR are not enforced (perhaps because there is no origin). 

It might exist for developer convenience when developing in a sandbox and in a test context if the original developers didn't know you could disable same origin policies in those places (run Chrome the `--disable-web-security` option and phantomjs with the `--web-security=false` option). The last reason I can think of is it being a backdoor for uploading results.
